require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SchoolDistrictsController do

  # This should return the minimal set of attributes required to create a valid
  # SchoolDistrict. As you add validations to SchoolDistrict, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SchoolDistrictsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all school_districts as @school_districts" do
      school_district = SchoolDistrict.create! valid_attributes
      get :index, {}, valid_session
      assigns(:school_districts).should eq([school_district])
    end
  end

  describe "GET show" do
    it "assigns the requested school_district as @school_district" do
      school_district = SchoolDistrict.create! valid_attributes
      get :show, {:id => school_district.to_param}, valid_session
      assigns(:school_district).should eq(school_district)
    end
  end

  describe "GET new" do
    it "assigns a new school_district as @school_district" do
      get :new, {}, valid_session
      assigns(:school_district).should be_a_new(SchoolDistrict)
    end
  end

  describe "GET edit" do
    it "assigns the requested school_district as @school_district" do
      school_district = SchoolDistrict.create! valid_attributes
      get :edit, {:id => school_district.to_param}, valid_session
      assigns(:school_district).should eq(school_district)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SchoolDistrict" do
        expect {
          post :create, {:school_district => valid_attributes}, valid_session
        }.to change(SchoolDistrict, :count).by(1)
      end

      it "assigns a newly created school_district as @school_district" do
        post :create, {:school_district => valid_attributes}, valid_session
        assigns(:school_district).should be_a(SchoolDistrict)
        assigns(:school_district).should be_persisted
      end

      it "redirects to the created school_district" do
        post :create, {:school_district => valid_attributes}, valid_session
        response.should redirect_to(SchoolDistrict.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved school_district as @school_district" do
        # Trigger the behavior that occurs when invalid params are submitted
        SchoolDistrict.any_instance.stub(:save).and_return(false)
        post :create, {:school_district => { "name" => "invalid value" }}, valid_session
        assigns(:school_district).should be_a_new(SchoolDistrict)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SchoolDistrict.any_instance.stub(:save).and_return(false)
        post :create, {:school_district => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested school_district" do
        school_district = SchoolDistrict.create! valid_attributes
        # Assuming there are no other school_districts in the database, this
        # specifies that the SchoolDistrict created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SchoolDistrict.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => school_district.to_param, :school_district => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested school_district as @school_district" do
        school_district = SchoolDistrict.create! valid_attributes
        put :update, {:id => school_district.to_param, :school_district => valid_attributes}, valid_session
        assigns(:school_district).should eq(school_district)
      end

      it "redirects to the school_district" do
        school_district = SchoolDistrict.create! valid_attributes
        put :update, {:id => school_district.to_param, :school_district => valid_attributes}, valid_session
        response.should redirect_to(school_district)
      end
    end

    describe "with invalid params" do
      it "assigns the school_district as @school_district" do
        school_district = SchoolDistrict.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SchoolDistrict.any_instance.stub(:save).and_return(false)
        put :update, {:id => school_district.to_param, :school_district => { "name" => "invalid value" }}, valid_session
        assigns(:school_district).should eq(school_district)
      end

      it "re-renders the 'edit' template" do
        school_district = SchoolDistrict.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SchoolDistrict.any_instance.stub(:save).and_return(false)
        put :update, {:id => school_district.to_param, :school_district => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested school_district" do
      school_district = SchoolDistrict.create! valid_attributes
      expect {
        delete :destroy, {:id => school_district.to_param}, valid_session
      }.to change(SchoolDistrict, :count).by(-1)
    end

    it "redirects to the school_districts list" do
      school_district = SchoolDistrict.create! valid_attributes
      delete :destroy, {:id => school_district.to_param}, valid_session
      response.should redirect_to(school_districts_url)
    end
  end

end
